1482749160695	Sync.Service	INFO	Loading Weave 1.49.0
1482749160697	Sync.Engine.Clients	DEBUG	Engine initialized
1482749160699	Sync.Engine.Clients	DEBUG	Resetting clients last sync time
1482749160704	Sync.Engine.Bookmarks	DEBUG	Engine initialized
1482749160708	Sync.Engine.Forms	DEBUG	Engine initialized
1482749160712	Sync.Engine.History	DEBUG	Engine initialized
1482749160717	Sync.Engine.Passwords	DEBUG	Engine initialized
1482749160720	Sync.Engine.Prefs	DEBUG	Engine initialized
1482749160724	Sync.Engine.Tabs	DEBUG	Engine initialized
1482749160725	Sync.Engine.Tabs	DEBUG	Resetting tabs last sync time
1482749160730	Sync.Engine.Addons	DEBUG	Engine initialized
1482749160731	Sync.Service	INFO	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
1482749160735	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1482749160736	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1482749160736	Sync.Service	DEBUG	Caching URLs under storage user base: https://sync-397-us-west-2.sync.services.mozilla.com/1.5/57197192/
1482749160736	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1482749160736	Sync.AddonsReconciler	INFO	Registering as Add-on Manager listener.
1482749160737	Sync.AddonsReconciler	DEBUG	Adding change listener.
1482749160737	Sync.Tracker.History	INFO	Adding Places observer.
1482749160782	browserwindow.syncui	DEBUG	observed: weave:service:ready
1482749160784	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1482749160786	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1482749160788	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1482749164791	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1482749164796	Sync.Service	DEBUG	User-Agent: Firefox/47.0.1 FxSync/1.49.0.20160710171639.
1482749164797	Sync.Service	INFO	Starting sync at 2016-12-26 17:46:04
1482749164797	Sync.Service	DEBUG	In sync: should login.
1482749164798	browserwindow.syncui	DEBUG	observed: weave:service:login:start
1482749164800	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1482749164800	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1482749164800	Sync.Service	INFO	Logging in the user.
1482749164805	Sync.BrowserIDManager	INFO	Waiting for user to be verified.
1482749164805	FirefoxAccounts	DEBUG	already verified
1482749164806	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1482749164808	Sync.BrowserIDManager	INFO	Starting fetch for key bundle.
1482749164809	FirefoxAccounts	DEBUG	already verified
1482749164810	Sync.BrowserIDManager	INFO	Getting an assertion from: https://token.services.mozilla.com/1.0/sync/1.5
1482749164810	FirefoxAccounts	DEBUG	enter getAssertion()
1482749164825	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1482749164832	FirefoxAccounts	DEBUG	got keyPair
1482749164832	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1482749166062	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms.
1482749166947	Sync.Tracker.Forms	DEBUG	Saving changed IDs to forms
1482749308636	FirefoxAccounts	ERROR	Could not retrieve profile data: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]"}
1482749308638	FirefoxAccounts	ERROR	Could not retrieve profile data: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]"}
1482749308641	FirefoxAccounts	ERROR	FxA rejecting with error NETWORK_ERROR, details: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]"}
1482749308642	FirefoxAccounts	ERROR	FxA rejecting with error NETWORK_ERROR, details: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]"}
1482749318674	Hawk	WARN	hawk request error: [Exception... "NS_ERROR_NET_TIMEOUT"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482"  data: no] Stack trace: onStopRequest()@resource://services-common/rest.js:482 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749318676	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 658"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:658 < _onComplete()@resource://services-common/hawkclient.js:222 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749318677	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 673"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:673 < _onComplete()@resource://services-common/hawkclient.js:225 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749318678	Hawk	DEBUG	(Response) /certificate/sign: code: null - Status text: null
1482749318678	Sync.RESTResponse	TRACE	Processing response headers.
1482749318678	Sync.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 705"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:705 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:318 < _onComplete()@resource://services-common/hawkclient.js:232 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749318680	Sync.RESTResponse	TRACE	Processing response headers.
1482749318680	Sync.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 705"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:705 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:318 < _onComplete()@resource://services-common/hawkclient.js:233 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749318682	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 673"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:673 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:125 < _onComplete()@resource://services-common/hawkclient.js:238 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749318683	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 658"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:658 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:126 < _onComplete()@resource://services-common/hawkclient.js:238 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749318684	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 658"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:658 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:127 < _onComplete()@resource://services-common/hawkclient.js:238 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749318685	Sync.RESTResponse	TRACE	Processing response headers.
1482749318685	Sync.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 705"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:705 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:132 < _onComplete()@resource://services-common/hawkclient.js:238 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749318687	FirefoxAccounts	ERROR	error POSTing /certificate/sign: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]","message":null,"code":null,"errno":null}
1482749318687	FirefoxAccounts	ERROR	HAWK.signCertificate error: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]","message":null,"code":null,"errno":null}
1482749318688	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]","message":null,"code":null,"errno":null}
1482749318688	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1482749318688	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1482749318689	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]","message":null,"code":null,"errno":null}
1482749360551	browserwindow.syncui	DEBUG	_loginFailed has sync state=error.login.reason.network
1482749360553	browserwindow.syncui	DEBUG	_loginFailed has sync state=error.login.reason.network
1482749360561	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1482749360561	FirefoxAccounts	DEBUG	getOAuthToken enter
1482749360562	FirefoxAccounts	TRACE	getCachedToken returning cached token
1482749360563	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1482749387749	Hawk	WARN	hawk request error: [Exception... "NS_ERROR_NET_TIMEOUT"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482"  data: no] Stack trace: onStopRequest()@resource://services-common/rest.js:482 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749387750	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 658"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:658 < _onComplete()@resource://services-common/hawkclient.js:222 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749387751	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 673"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:673 < _onComplete()@resource://services-common/hawkclient.js:225 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749387752	Hawk	DEBUG	(Response) /account/status?uid=3fd940bb3e6d43389f144d37bfea0402: code: null - Status text: null
1482749387752	Sync.RESTResponse	TRACE	Processing response headers.
1482749387753	Sync.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 705"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:705 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:318 < _onComplete()@resource://services-common/hawkclient.js:232 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749387754	Sync.RESTResponse	TRACE	Processing response headers.
1482749387754	Sync.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 705"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:705 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:318 < _onComplete()@resource://services-common/hawkclient.js:233 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749387755	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 673"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:673 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:125 < _onComplete()@resource://services-common/hawkclient.js:238 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749387756	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 658"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:658 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:126 < _onComplete()@resource://services-common/hawkclient.js:238 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749387757	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 658"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:658 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:127 < _onComplete()@resource://services-common/hawkclient.js:238 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749387758	Sync.RESTResponse	TRACE	Processing response headers.
1482749387759	Sync.RESTResponse	DEBUG	Caught exception processing response headers: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 705"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:705 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:132 < _onComplete()@resource://services-common/hawkclient.js:238 < onComplete()@resource://services-common/hawkclient.js:279 < onStopRequest()@resource://services-common/rest.js:484 < waitForSyncCallback()@resource://services-common/async.js:98 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:152 < onNotify()@resource://services-sync/service.js:966 < WrappedNotify()@resource://services-sync/util.js:146 < WrappedLock()@resource://services-sync/util.js:101 < WrappedCatch()@resource://services-sync/util.js:75 < login()@resource://services-sync/service.js:988 < sync/<()@resource://services-sync/service.js:1236 < WrappedCatch()@resource://services-sync/util.js:75 < sync()@resource://services-sync/service.js:1232
1482749387760	FirefoxAccounts	ERROR	error GETing /account/status?uid=3fd940bb3e6d43389f144d37bfea0402: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]","message":null,"code":null,"errno":null}
1482749387760	FirefoxAccounts	ERROR	accountStatus failed with: null: null
1482749387762	Sync.BrowserIDManager	ERROR	Error while trying to determine FXA existence: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]","message":null,"code":null,"errno":null}
1482749387762	Sync.BrowserIDManager	ERROR	Could not authenticate: {"error":{},"errorString":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 482\"  data: no]","message":null,"code":null,"errno":null}
1482749387764	browserwindow.syncui	DEBUG	observed: weave:service:login:error
1482749387764	browserwindow.syncui	DEBUG	onLoginError: login=error.login.reason.network, sync=success.sync
1482749387765	browserwindow.syncui	DEBUG	observed: weave:service:login:error
1482749387765	browserwindow.syncui	DEBUG	onLoginError: login=error.login.reason.network, sync=success.sync
1482749387766	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1482749387767	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms.
1482749387768	Sync.ErrorHandler	ERROR	Sync encountered a login error
